#!/usr/bin/env bash
# SSL Enable Script Template
# Generated by create-docker-agent when SSL is requested
# Usage: ./enable-ssl.sh <domain> <email>

set -euo pipefail

DOMAIN=${1:-}
EMAIL=${2:-}

if [ -z "$DOMAIN" ] || [ -z "$EMAIL" ]; then
  echo "Usage: ./enable-ssl.sh <domain> <email>"
  exit 1
fi

echo "[+] Generating Diffie-Hellman parameters..."
mkdir -p ./dhparam
if [ ! -f ./dhparam/dhparam.pem ]; then
  openssl dhparam -out ./dhparam/dhparam.pem 2048
  echo "[✓] Diffie-Hellman parameters generated"
else
  echo "[✓] Diffie-Hellman parameters already exist"
fi

echo "[+] Creating ACME challenge directory..."
mkdir -p ./letsencrypt

echo "[+] Running certbot for domain: $DOMAIN"
docker compose run --rm certbot certonly \
  --webroot --webroot-path=/var/www/letsencrypt \
  --email "$EMAIL" --agree-tos --no-eff-email \
  -d "$DOMAIN"

echo "[+] Reloading Nginx to apply SSL configuration"
docker compose restart nginx

echo "[✓] SSL enabled successfully!"
echo "[!] Remember to set up automatic renewal:"
echo "    Add to crontab: 0 3 * * * cd $(pwd) && docker compose run --rm certbot renew && docker compose kill -s HUP nginx"

